/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2023年终总结以及我个人杂七杂八的事情1': RouteRecordInfo<'/posts/2023年终总结以及我个人杂七杂八的事情1', '/posts/2023年终总结以及我个人杂七杂八的事情1', Record<never, never>, Record<never, never>>,
    '/posts/大学第一天——意外的老油条之旅1': RouteRecordInfo<'/posts/大学第一天——意外的老油条之旅1', '/posts/大学第一天——意外的老油条之旅1', Record<never, never>, Record<never, never>>,
    '/posts/番剧列表': RouteRecordInfo<'/posts/番剧列表', '/posts/番剧列表', Record<never, never>, Record<never, never>>,
    '/posts/孤独群候症': RouteRecordInfo<'/posts/孤独群候症', '/posts/孤独群候症', Record<never, never>, Record<never, never>>,
    '/posts/关于性别认同--为何想成为药娘呢1': RouteRecordInfo<'/posts/关于性别认同--为何想成为药娘呢1', '/posts/关于性别认同--为何想成为药娘呢1', Record<never, never>, Record<never, never>>,
    '/posts/过去': RouteRecordInfo<'/posts/过去', '/posts/过去', Record<never, never>, Record<never, never>>,
    '/posts/幻梦，死于现实，亦或是软弱': RouteRecordInfo<'/posts/幻梦，死于现实，亦或是软弱', '/posts/幻梦，死于现实，亦或是软弱', Record<never, never>, Record<never, never>>,
    '/posts/荒原的故事': RouteRecordInfo<'/posts/荒原的故事', '/posts/荒原的故事', Record<never, never>, Record<never, never>>,
    '/posts/决定写一点流水账的日记！': RouteRecordInfo<'/posts/决定写一点流水账的日记！', '/posts/决定写一点流水账的日记！', Record<never, never>, Record<never, never>>,
    '/posts/跨年1': RouteRecordInfo<'/posts/跨年1', '/posts/跨年1', Record<never, never>, Record<never, never>>,
    '/posts/另世我': RouteRecordInfo<'/posts/另世我', '/posts/另世我', Record<never, never>, Record<never, never>>,
    '/posts/严重的焦虑与抑郁1': RouteRecordInfo<'/posts/严重的焦虑与抑郁1', '/posts/严重的焦虑与抑郁1', Record<never, never>, Record<never, never>>,
    '/posts/意外的多了很多感慨1': RouteRecordInfo<'/posts/意外的多了很多感慨1', '/posts/意外的多了很多感慨1', Record<never, never>, Record<never, never>>,
    '/posts/怨念': RouteRecordInfo<'/posts/怨念', '/posts/怨念', Record<never, never>, Record<never, never>>,
    '/posts/云南之旅1': RouteRecordInfo<'/posts/云南之旅1', '/posts/云南之旅1', Record<never, never>, Record<never, never>>,
    '/posts/First': RouteRecordInfo<'/posts/First', '/posts/First', Record<never, never>, Record<never, never>>,
    '/posts/HRT100days自己的生活发生什么变化了吗1': RouteRecordInfo<'/posts/HRT100days自己的生活发生什么变化了吗1', '/posts/HRT100days自己的生活发生什么变化了吗1', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
